In [42]:
import requests
from os import environ as env
from bs4 import BeautifulSoup

In [43]:
key=env.get('e7b8d01640d7db313d377f7daac5c193')
url=f'http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieList.xml?key=e7b8d01640d7db313d377f7daac5c193'

In [44]:
response = requests.get(url)
xml_data=response.content
soup=BeautifulSoup(xml_data, 'xml')

In [45]:
movies = soup.find_all('movie')

In [46]:
movies_list=[]

In [47]:
movies_list = []

for movie in movies:
    movieCd_tag = movie.find('movieCd') #영화코드
    movieCd = movieCd_tag.text if movieCd_tag is not None else None

    movieNm_tag = movie.find('movieNm') # 영화명(국문)
    movieNm = movieNm_tag.text if movieNm_tag is not None else None

    movieNmEn_tag = movie.find('movieNmEn') # 영화명(영문)
    movieNmEn = movieNmEn_tag.text if movieNmEn_tag is not None else None

    openDt_tag = movie.find('openDt') # 개봉일
    openDt = openDt_tag.text if openDt_tag is not None else None

    nationAlt_tag = movie.find('nationAlt')# 제작국가
    nationAlt = nationAlt_tag.text if nationAlt_tag is not None else None

    genreAlt_tag = movie.find('genreAlt')# 장르
    genreAlt = genreAlt_tag.text if genreAlt_tag is not None else None

    peopleNm_tag = movie.find('peopleNm')# 감독
    peopleNm = peopleNm_tag.text if peopleNm_tag is not None else None

    movies_list.append({'movieCd': movieCd, 'movieNm': movieNm, 'movieNmEn': movieNmEn,
                        'openDt': openDt, 'nationAlt': nationAlt, 'genreAlt': genreAlt, 'peopleNm': peopleNm})

In [41]:
movies_list

[{'movieCd': '20240103',
  'movieNm': '멜팅포인트',
  'movieNmEn': 'MeltingPoint',
  'openDt': '',
  'nationAlt': '한국',
  'genreAlt': '기타',
  'peopleNm': '송현석'},
 {'movieCd': '20240355',
  'movieNm': '욕정에 미친 그녀',
  'movieNmEn': '',
  'openDt': '',
  'nationAlt': '한국',
  'genreAlt': '성인물(에로)',
  'peopleNm': None},
 {'movieCd': '20240374',
  'movieNm': '내 여동생과 섹스해 줘',
  'movieNmEn': '',
  'openDt': '',
  'nationAlt': '한국',
  'genreAlt': '성인물(에로)',
  'peopleNm': None},
 {'movieCd': '20240356',
  'movieNm': '불륜에 중독된 변태 유부녀',
  'movieNmEn': '',
  'openDt': '',
  'nationAlt': '한국',
  'genreAlt': '성인물(에로)',
  'peopleNm': None},
 {'movieCd': '20240357',
  'movieNm': '남동생마저 노리는 욕정녀',
  'movieNmEn': '',
  'openDt': '',
  'nationAlt': '한국',
  'genreAlt': '성인물(에로)',
  'peopleNm': None},
 {'movieCd': '20240371',
  'movieNm': '성욕이 너무 강한 글래머',
  'movieNmEn': '',
  'openDt': '',
  'nationAlt': '한국',
  'genreAlt': '성인물(에로)',
  'peopleNm': None},
 {'movieCd': '20240372',
  'movieNm': '처음 본 대물에 젖어버린 유부녀',
  'movieNmEn': '',
  'openDt': '',
  'nationAlt': '한국',
  'genreAlt': '성인물(에로)',
  'peopleNm': None},
 {'movieCd': '20240373',
  'movieNm': '운동하는 후배를 탐하는 여선배',
  'movieNmEn': '',
  'openDt': '',
  'nationAlt': '한국',
  'genreAlt': '성인물(에로)',
  'peopleNm': None},
 {'movieCd': '20240354',
  'movieNm': '역대급 슬렌더 미녀의 섹스',
  'movieNmEn': '',
  'openDt': '',
  'nationAlt': '한국',
  'genreAlt': '성인물(에로)',
  'peopleNm': None},
 {'movieCd': '20240369',
  'movieNm': '잠든 형부를 맛보는 처제',
  'movieNmEn': '',
  'openDt': '',
  'nationAlt': '한국',
  'genreAlt': '성인물(에로)',
  'peopleNm': None}]

In [1]:
pip install xlrd

Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl.metadata (3.4 kB)
Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
   ---------------------------------------- 0.0/96.5 kB ? eta -:--:--
   ------------ --------------------------- 30.7/96.5 kB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 96.5/96.5 kB 2.7 MB/s eta 0:00:00
Installing collected packages: xlrd
Successfully installed xlrd-2.0.1
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\anaconnda3\lib\site-packages (3.0.10)
Requirement already satisfied: et_xmlfile in c:\anaconnda3\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip install pandas

Requirement already satisfied: pandas in c:\anaconnda3\lib\site-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.23.2 in c:\anaconnda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\anaconnda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\anaconnda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\anaconnda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\anaconnda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [12]:
import pandas as pd
file_name='movieList.xls'
df = pd.read_excel(file_name)
df

,영화명,영화명(영문),제작연도,제작국가,유형,장르,제작상태,감독,제작사
0,이중노출,NaN,2024.0,한국,장편,성인물(에로),기타,NaN,대박필름
1,멜팅포인트,MeltingPoint,2024.0,한국,장편,기타,기타,송현석,NaN
2,욕정에 미친 그녀,NaN,2024.0,한국,장편,성인물(에로),개봉예정,NaN,(주)샤이커뮤니케이션즈
3,내 여동생과 섹스해 줘,NaN,2024.0,한국,장편,성인물(에로),개봉예정,NaN,(주)샤이커뮤니케이션즈
4,불륜에 중독된 변태 유부녀,NaN,2024.0,한국,장편,성인물(에로),개봉예정,NaN,(주)샤이커뮤니케이션즈
...,...,...,...,...,...,...,...,...,...
65526,최종면접,Last Interview,2012.0,한국,단편,드라마,기타,현문섭,NaN
65527,플라멩코 소녀,Flamenco Nina,2013.0,한국,단편,드라마,기타,이찬호,NaN
65528,KTX 특별열차,KTX Extra,2009.0,한국,단편,드라마,기타,정수진,NaN
65529,무더운 하루,NaN,2013.0,한국,단편,기타,기타,NaN,NaN
65530,그남자 그여자의 면접,NaN,2013.0,한국,단편,기타,기타,NaN,NaN

In [1]:
import pymysql

In [4]:
pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.1.0-py3-none-any.whl.metadata (4.4 kB)
Downloading PyMySQL-1.1.0-py3-none-any.whl (44 kB)
   ---------------------------------------- 0.0/44.8 kB ? eta -:--:--
   --------- ------------------------------ 10.2/44.8 kB ? eta -:--:--
   ---------------------------------------- 44.8/44.8 kB 1.1 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.0
Note: you may need to restart the kernel to use updated packages.

In [6]:
# db생성
db = pymysql.connect(host='127.0.0.1', user='root', password='1234')
cursor = db.cursor()

try:
    cursor.execute('create database Movie_DB;')
    db.commit()
    db.close()
    print('has been created')
except:
    print('Database already exsist!')

Database already exsist!

In [16]:
# sqlalchemy를 사용해 원하는 database에 csv파일 저장
from sqlalchemy import create_engine

try:
    engine = create_engine("mysql+pymysql://root:"+"1234"+
                           "@127.0.0.1:3306/Movie_DB?charset=utf8")
    conn = engine.connect()
    df.to_sql(name = "영화", con = engine, index = False)
    conn.close()
    
except ValueError:
    print('Table already exists!')

In [19]:
#db 및 테이블연동
import pymysql

db = pymysql.connect(user='root', password='1234', host='127.0.0.1', db='Movie_DB', cursorclass=pymysql.cursors.DictCursor)

cursor = db.cursor()

query = "select * from movie_db.영화"
cursor.execute(query)
db_export = cursor.fetchall()

In [21]:
# dataframe 입력
import pandas as pd
db_result_df=pd.DataFrame(db_export)
db_result_df

,영화명,영화명(영문),제작연도,제작국가,유형,장르,제작상태,감독,제작사
0,이중노출,None,2024.0,한국,장편,성인물(에로),기타,None,대박필름
1,멜팅포인트,MeltingPoint,2024.0,한국,장편,기타,기타,송현석,None
2,욕정에 미친 그녀,None,2024.0,한국,장편,성인물(에로),개봉예정,None,(주)샤이커뮤니케이션즈
3,내 여동생과 섹스해 줘,None,2024.0,한국,장편,성인물(에로),개봉예정,None,(주)샤이커뮤니케이션즈
4,불륜에 중독된 변태 유부녀,None,2024.0,한국,장편,성인물(에로),개봉예정,None,(주)샤이커뮤니케이션즈
...,...,...,...,...,...,...,...,...,...
65526,최종면접,Last Interview,2012.0,한국,단편,드라마,기타,현문섭,None
65527,플라멩코 소녀,Flamenco Nina,2013.0,한국,단편,드라마,기타,이찬호,None
65528,KTX 특별열차,KTX Extra,2009.0,한국,단편,드라마,기타,정수진,None
65529,무더운 하루,None,2013.0,한국,단편,기타,기타,None,None
65530,그남자 그여자의 면접,None,2013.0,한국,단편,기타,기타,None,None